// Code generated by counterfeiter. DO NOT EDIT.
package gravelmapfakes

import (
	"sync"

	"github.com/thanosKontos/gravelmap"
)

type FakeElevationGetterCloser struct {
	CloseStub        func()
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	GetStub        func([]gravelmap.Point, float64) (*gravelmap.WayElevation, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 []gravelmap.Point
		arg2 float64
	}
	getReturns struct {
		result1 *gravelmap.WayElevation
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *gravelmap.WayElevation
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeElevationGetterCloser) Close() {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		fake.CloseStub()
	}
}

func (fake *FakeElevationGetterCloser) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeElevationGetterCloser) CloseCalls(stub func()) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeElevationGetterCloser) Get(arg1 []gravelmap.Point, arg2 float64) (*gravelmap.WayElevation, error) {
	var arg1Copy []gravelmap.Point
	if arg1 != nil {
		arg1Copy = make([]gravelmap.Point, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 []gravelmap.Point
		arg2 float64
	}{arg1Copy, arg2})
	fake.recordInvocation("Get", []interface{}{arg1Copy, arg2})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeElevationGetterCloser) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeElevationGetterCloser) GetCalls(stub func([]gravelmap.Point, float64) (*gravelmap.WayElevation, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeElevationGetterCloser) GetArgsForCall(i int) ([]gravelmap.Point, float64) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeElevationGetterCloser) GetReturns(result1 *gravelmap.WayElevation, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *gravelmap.WayElevation
		result2 error
	}{result1, result2}
}

func (fake *FakeElevationGetterCloser) GetReturnsOnCall(i int, result1 *gravelmap.WayElevation, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *gravelmap.WayElevation
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *gravelmap.WayElevation
		result2 error
	}{result1, result2}
}

func (fake *FakeElevationGetterCloser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeElevationGetterCloser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gravelmap.ElevationGetterCloser = new(FakeElevationGetterCloser)
